### ISSUE TITLE
Map initial configuration

### ISSUE THREAD

**Issue by cruizm** [NMAI-lab/SAVI#75] opened 2019-02-01 16:26 UTC
Instead of having threats, world objects and agents place randomly, have different map configurations predefined in a "map file".  Make the map file a line in the configuration file

**Comment by pgavigan** [comment] 2019-03-22 22:12
Duplicate of https://github.com/NMAI-lab/SAVI/issues/118.

**Closed by pgavigan** 2019-03-22 22:12 UTC
Labels: duplicate
